import Head from 'next/head'
import { About } from '../components/About'
import { BodyComp } from '../components/BodyComp'
import { Education } from '../components/Education'
import { Navbar } from '../components/Navbar'
import { Skills } from '../components/Skills'
import { Projects } from '../components/Projects'
import { Contact } from '../components/Contact'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Vutlhari Mashimbyi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <BodyComp/>
     <About/>
      <Skills/>
      <Education/>
      <Projects/>
      <Contact/>
    </div>
  )
}
